### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by Habinbottoms** [TheWii/immersive-soundscapes#4]
You should make a menu that allows users to enable to disable certain sounds beyond soundtracks. I personally don't like it making a swish every time I jump as I like to sprint jump a lot and I'm sure others may have different preferences.

**Comment by TheWii** [comment]
Hey, sorry for the late answer. I can consider working on a dynamic way to disable certain sounds, for example the jumping sound you mentioned, it's 100% possible to add a way to turn it on/off, but unfortunately some sounds are hardcoded in the resource pack, so the only way is modifying the files manually. Thanks for the suggestion.

**Comment by Capybarman** [comment]
Please help with the installation, I do everything according to the instructions, I put the files immersive-soundscapes-datapack-v2.4.zip and immersive-soundscapes-resources-v2.4.zip from assets into the datapack folder, but it just doesn’t work even the command / reload doesn't help no matter what i do

**Comment by WilczaQ** [comment]
> Please help with the installation, I do everything according to the instructions, I put the files immersive-soundscapes-datapack-v2.4.zip and immersive-soundscapes-resources-v2.4.zip from assets into the datapack folder, but it just doesn’t work even the command / reload doesn't help no matter what i do

immersive-soundscapes-datapack-v2.4.zip to the folder: .minecraft/saves/*name*/datapacks
immersive-soundscapes-resources-v2.4.zip to the folder: .minecraft/resourcepacks/ :)
